interface CaseSummary {
  case_number: string
  status: string
  soap_note: {
    subjective: string
    objective: string
    assessment: string
    plan: string
    disclaimer: string
  } | null
  icd_codes: string[] | null
  escalated: boolean
}

interface Props {
  summary: CaseSummary
}

export default function PrintableReport({ summary }: Props) {
  if (!summary.soap_note) return null

  return (
    <div className="bg-white p-8 rounded-xl shadow-sm print:shadow-none print:p-0">
      {/* Print header */}
      <div className="text-center mb-6 print:mb-4">
        <h1 className="text-2xl font-bold">Patient Advocacy Agent</h1>
        <p className="text-sm text-gray-500">Clinical Case Report</p>
        <p className="font-mono text-sm mt-1">{summary.case_number}</p>
      </div>

      {summary.escalated && (
        <div className="bg-red-50 border-2 border-red-500 p-3 mb-6 text-center rounded-lg print:border-black">
          <p className="font-bold text-red-800 print:text-black">ESCALATED: Suspected Malignancy — Immediate Review Required</p>
        </div>
      )}

      <div className="space-y-6">
        {(['subjective', 'objective', 'assessment', 'plan'] as const).map((section) => (
          <div key={section}>
            <h2 className="text-sm font-bold uppercase text-gray-700 border-b pb-1 mb-2">{section}</h2>
            <p className="text-sm whitespace-pre-wrap">{summary.soap_note?.[section]}</p>
          </div>
        ))}
      </div>

      {summary.icd_codes && summary.icd_codes.length > 0 && (
        <div className="mt-6">
          <h2 className="text-sm font-bold uppercase text-gray-700 border-b pb-1 mb-2">ICD-10 Codes</h2>
          <p className="font-mono text-sm">{summary.icd_codes.join(', ')}</p>
        </div>
      )}

      <div className="mt-8 pt-4 border-t">
        <p className="text-xs text-red-600 italic">
          {summary.soap_note.disclaimer || 'DISCLAIMER: This system is NOT a doctor. Always seek professional medical help. This report is for informational purposes only.'}
        </p>
      </div>

      {/* Print-only footer */}
      <div className="hidden print:block mt-8 text-center text-xs text-gray-500">
        <p>Generated by Patient Advocacy Agent &mdash; {new Date().toLocaleString()}</p>
      </div>
    </div>
  )
}
